<a href="https://colab.research.google.com/github/tuananh1006/Web-Scraping-Book/blob/main/PreprocessCountryData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import csv
from urllib.request import urlopen
from bs4 import BeautifulSoup

html = urlopen('https://en.wikipedia.org/wiki/List_of_countries_with_McDonald%27s_restaurants')
bs = BeautifulSoup(html, 'html.parser')
# The main comparison table is currently the first table on the page
table = bs.find_all('table',{'class':'wikitable'})[0]
rows = table.findAll('tr')
csvFile = open('countries.csv', 'wt+')
writer = csv.writer(csvFile)
try:
    for row in rows:
        csvRow = []
        for cell in row.findAll(['td', 'th']):
          a=cell.find('a',{'rel':'nofollow'})
          if a:
            csvRow.append(a['href'])
          else:
            csvRow.append(cell.get_text().strip())
        writer.writerow(csvRow)
finally:
    csvFile.close()

In [57]:
import pandas as pd
df=pd.read_csv('countries.csv')

In [58]:
df.rename(columns={
    '#': 'Order',
    'Country/territory': 'Country',
    'Date of first store': 'Date',
    'First outlet location': 'Location',
    'Max. no. ofoperatingoutlets': 'Outlets'
}, inplace=True)

In [37]:
df.head(10)

,Order,Country,Date,Location,Outlets,Source and date of source,People per outlet,Notes
0,1,United States,"May 15, 1940Franchise: April 15, 1955","San Bernardino, CaliforniaDes Plaines, Illinoi...","13,449","(source: Corporate McDonald's December 31, 202...","25,539",https://www.mcdonalds.com/us/en-us.html
1,2,Canada (details),"June 3, 1967","Richmond, British Columbia(Reopened June 23, 2...","1,466","(source: Corporate McDonald's December 31, 202...","28,807",https://www.mcdonalds.com/ca/en-ca.html
2,3,Puerto Rico(territory of United States),"November 10, 1967",San Juan,95,"(source: Corporate McDonald's December 31, 202...","34,127",http://www.mcdonalds.com.pr/
3,4,United States Virgin Islands(territory of Unit...,"September 5, 1970",St. Croix,5,"(source: Corporate McDonald's December 31, 202...","17,140",NaN
4,5,Costa Rica,"December 8, 1970","San Jos√©, 4th street, between 1st and Central ...",73,"(source: Corporate McDonald's December 31, 202...","69,939",http://www.mcdonalds.co.cr/
5,6,Australia,"May 30, 1971","Yagoona, New South Wales[13]","1,032","(source: Corporate McDonald's December 31, 202...","25,631",https://mcdonalds.com.au/
6,7,Guam(territory of United States),"June 10, 1971",Dededo,5,"(source: Corporate McDonald's December 31, 202...","33,301",https://www.mcdonaldsguamandsaipan.com/
7,8,Japan,"July 21, 1971","Ginza Mitsukoshi, Ginza, Chuo City, Tokyo","2,982","(source: Corporate McDonald's December 31, 202...","41,707",https://www.mcdonalds.co.jp/
8,9,Netherlands,"August 21, 1971",Zaandam,263[16],"(source: Corporate McDonald's December 31, 202...","68,793",https://www.mcdonalds.com/nl/nl-nl.html
9,10,Panama,"September 1, 1971",Panama City,81,"(source: Corporate McDonald's December 31, 202...","55,046",http://www.mcdonalds.com.pa/

In [67]:
df= df[['Order', 'Country', 'Date', 'Location', 'Outlets']]

In [68]:
df.head(5)

,Order,Country,Date,Location,Outlets
0,1,United States,"May 15, 1940Franchise: April 15, 1955","San Bernardino, CaliforniaDes Plaines, Illinoi...","13,449"
1,2,Canada (details),"June 3, 1967","Richmond, British Columbia(Reopened June 23, 2...","1,466"
2,3,Puerto Rico(territory of United States),"November 10, 1967",San Juan,95
3,4,United States Virgin Islands(territory of Unit...,"September 5, 1970",St. Croix,5
4,5,Costa Rica,"December 8, 1970","San Jos√©, 4th street, between 1st and Central ...",73

In [87]:
date_regex = re.compile('[A-Z][a-z]+ [0-9]{1,2}, +[0-9]{4}')
CITATION_REGEX = re.compile('\[[0-9]*\]')
def strip_citations(text):
    return re.sub(CITATION_REGEX, '', text)
date_regex.findall(strip_citations(df['Date'][113]))

['December 29,  2014']

In [88]:
import re

date_regex = re.compile('[A-Z][a-z]+ [0-9]{1,2}, +[0-9]{4}')

In [90]:
try:
  df['Date'] = df['Date'].apply(lambda d: date_regex.findall(d)[0])
except IndexError as e:
  print(e)

In [91]:
df['Date'] = pd.to_datetime(df['Date'])

In [92]:
df.head(10)

,Order,Country,Date,Location,Outlets,DateNew
0,1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...","13,449",2
1,2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...","1,466",1
2,3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
3,4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
4,5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
5,6,Australia,1971-05-30,"Yagoona, New South Wales[13]","1,032",1
6,7,Guam(territory of United States),1971-06-10,Dededo,5,1
7,8,Japan,1971-07-21,"Ginza Mitsukoshi, Ginza, Chuo City, Tokyo","2,982",1
8,9,Netherlands,1971-08-21,Zaandam,263[16],1
9,10,Panama,1971-09-01,Panama City,81,1

In [93]:
int_regex = re.compile('[0-9,]+')

def str_to_int(s):
    s = int_regex.findall(s)[0]
    s = s.replace(',','')
    return int(s)

df['Outlets'] = df['Outlets'].apply(str_to_int)

In [94]:
df.head(5)

,Order,Country,Date,Location,Outlets,DateNew
0,1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
1,2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
2,3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
3,4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
4,5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1

In [95]:
def str_to_int(s):
    try:
        s = int_regex.findall(s)[0]
        s = s.replace(',','')
    except:
        print(f'Whoops: {s}')
    return int(s)

In [96]:
df.set_index(['Order'], inplace=True)
df.head()

,Country,Date,Location,Outlets,DateNew
Order,,,,,
1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1

In [97]:
df.sort_values(by=['Outlets', 'Date'], ascending=False)

,Country,Date,Location,Outlets,DateNew
Order,,,,,
1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
48,China,1990-10-08,"Dongmen, Luohu District, Shenzhen",5903,1
8,Japan,1971-07-21,"Ginza Mitsukoshi, Ginza, Chuo City, Tokyo",2982,1
12,France (details),1972-06-30,Cr√©teil,1559,1
2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
...,...,...,...,...,...
96,Jersey(British Crown dependency),1997-08-01,Saint Helier,1,1
85,Liechtenstein,1996-05-03,Triesen,1,1
83,Samoa(named Western Samoa at the time),1996-03-02,Apia,1,1
58,Monaco,1992-11-20,Monte Carlo,1,1
41,Cuba,1986-04-24,Guantanamo Bay,1,1

In [98]:
df.query('Outlets < 100')

,Country,Date,Location,Outlets,DateNew
Order,,,,,
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
7,Guam(territory of United States),1971-06-10,Dededo,5,1
10,Panama,1971-09-01,Panama City,81,1
...,...,...,...,...,...
111,Mauritius,2001-07-04,Port Louis,16,1
112,Iraq,2006-08-10,Baghdad,1,1
113,Vietnam,2014-02-08,Ho Chi Minh City,33,1
114,Saint Martin (territory of France),2014-12-29,Marigot,1,1
115,Western Sahara (Area occupied by Morocco),2017-08-10,Laayoune,1,1

In [105]:
df.query('Date != None')

,Country,Date,Location,Outlets,DateNew
Order,,,,,
1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
...,...,...,...,...,...
111,Mauritius,2001-07-04,Port Louis,16,1
112,Iraq,2006-08-10,Baghdad,1,1
113,Vietnam,2014-02-08,Ho Chi Minh City,33,1
114,Saint Martin (territory of France),2014-12-29,Marigot,1,1
115,Western Sahara (Area occupied by Morocco),2017-08-10,Laayoune,1,1

In [106]:
df.query('Date.isnull()')
df.query('Date.notnull()')

,Country,Date,Location,Outlets,DateNew
Order,,,,,
1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
...,...,...,...,...,...
111,Mauritius,2001-07-04,Port Louis,16,1
112,Iraq,2006-08-10,Baghdad,1,1
113,Vietnam,2014-02-08,Ho Chi Minh City,33,1
114,Saint Martin (territory of France),2014-12-29,Marigot,1,1
115,Western Sahara (Area occupied by Morocco),2017-08-10,Laayoune,1,1

In [107]:
df.query('Outlets < 100 & Date < "01-06-1990"')

,Country,Date,Location,Outlets,DateNew
Order,,,,,
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
7,Guam(territory of United States),1971-06-10,Dededo,5,1
10,Panama,1971-09-01,Panama City,81,1
13,El Salvador,1972-07-20,San Salvador,22,1
16,Cura√ßao(part of Netherlands Antilles at the time),1974-08-16,Willemstad,5,1
19,Bahamas,1975-08-04,Nassau,3,1
22,Ireland,1977-05-09,"Grafton Street, Dublin",95,1
31,Norway,1983-11-18,"Nedre Slottsgate, Oslo",79,1
33,Andorra,1984-06-29,Andorra la Vella,5,1
34,Finland,1984-12-14,"H√§meenkatu 17, Tampere",75,1
37,Aruba(part of Netherlands Antilles at the time),1985-04-04,Oranjestad,3,1
38,Luxembourg,1985-07-17,Luxembourg City,12,1
39,Venezuela,1985-08-31,"El Rosal, Caracas (now closed)",83,1
41,Cuba,1986-04-24,Guantanamo Bay,1,1
44,Macau(Portuguese Macau at the time),1987-04-11,"Rua do Campo, Cathedral Parish, Macau Peninsula",39,1
45,Serbia(part of Yugoslavia at the time),1988-03-24,"Slavija Square, Belgrade",33,1

In [108]:
df.query('Outlets < 100 | Date < "01-06-1990"')

,Country,Date,Location,Outlets,DateNew
Order,,,,,
1,United States,1940-05-15,"San Bernardino, CaliforniaDes Plaines, Illinoi...",13449,2
2,Canada (details),1967-06-03,"Richmond, British Columbia(Reopened June 23, 2...",1466,1
3,Puerto Rico(territory of United States),1967-11-10,San Juan,95,1
4,United States Virgin Islands(territory of Unit...,1970-09-05,St. Croix,5,1
5,Costa Rica,1970-12-08,"San Jos√©, 4th street, between 1st and Central ...",73,1
...,...,...,...,...,...
111,Mauritius,2001-07-04,Port Louis,16,1
112,Iraq,2006-08-10,Baghdad,1,1
113,Vietnam,2014-02-08,Ho Chi Minh City,33,1
114,Saint Martin (territory of France),2014-12-29,Marigot,1,1
115,Western Sahara (Area occupied by Morocco),2017-08-10,Laayoune,1,1